window.YC_API = "https://painel-fazenda-pirassununga.vercel.app";
window.YC_UNIVERSE = [
  { s: "BRL=X", show: "USDBRL", n: "Dólar / Real", tab: "fx", group: "Câmbio", q: 100, fmt: "fx" },
  { s: "EURBRL=X", show: "EURBRL", n: "Euro / Real", tab: "fx", group: "Câmbio", q: 90, fmt: "fx" },
  { s: "CTZ26.NYB", show: "CTZ26", n: "Algodão Dez/26", tab: "agro", group: "Algodão", q: 99, fmt: "usd" },
  { s: "CTZ27.NYB", show: "CTZ27", n: "Algodão Dez/27", tab: "agro", group: "Algodão", q: 98, fmt: "usd" },
  { s: "CTZ28.NYB", show: "CTZ28", n: "Algodão Dez/28", tab: "agro", group: "Algodão", q: 97, fmt: "usd" },
  { s: "ZSH26.CBT", show: "ZSH26", n: "Soja Mar/26", tab: "agro", group: "Soja", q: 96, fmt: "usd" },
  { s: "ZSH27.CBT", show: "ZSH27", n: "Soja Mar/27", tab: "agro", group: "Soja", q: 95, fmt: "usd" },
  { s: "ZSH28.CBT", show: "ZSH28", n: "Soja Mar/28", tab: "agro", group: "Soja", q: 94, fmt: "usd" },
  { s: "CT=F", show: "CT=F", n: "Algodão à vista", tab: "agro", group: "Algodão", q: 88, fmt: "usd" },
  { s: "ZS=F", show: "ZS=F", n: "Soja Chicago", tab: "agro", group: "Soja", q: 87, fmt: "usd" },
  { s: "ZC=F", show: "ZC=F", n: "Milho Chicago", tab: "agro", group: "Milho", q: 86, fmt: "usd" },
  { s: "IMEA-SOJA", show: "SOJA", n: "Soja IMEA", tab: "agro", group: "Praça", q: 85, fmt: "brl" },
  { s: "IMEA-MILHO", show: "MILHO", n: "Milho IMEA", tab: "agro", group: "Praça", q: 84, fmt: "brl" },
  { s: "IMEA-ALGODAO", show: "PLUMA", n: "Algodão IMEA", tab: "agro", group: "Praça", q: 83, fmt: "brl" },
  { s: "IMEA-BOI", show: "BOI", n: "Boi gordo IMEA", tab: "agro", group: "Praça", q: 82, fmt: "brl" },
  { s: "BZ=F", show: "BRENT", n: "Petróleo Brent", tab: "agro", group: "Energia", q: 81, fmt: "usd" },
  { s: "GC=F", show: "OURO", n: "Ouro spot", tab: "fx", group: "Metal", q: 80, fmt: "usd" },
  { s: "ITUB4.SA", show: "ITUB4", n: "Itaú", tab: "b3", group: "Bancos", q: 79, fmt: "brl" },
  { s: "BBDC4.SA", show: "BBDC4", n: "Bradesco", tab: "b3", group: "Bancos", q: 78, fmt: "brl" },
  { s: "BBAS3.SA", show: "BBAS3", n: "Banco do Brasil", tab: "b3", group: "Bancos", q: 77, fmt: "brl" },
  { s: "PETR4.SA", show: "PETR4", n: "Petrobras", tab: "b3", group: "Energia", q: 76, fmt: "brl" },
  { s: "VALE3.SA", show: "VALE3", n: "Vale", tab: "b3", group: "Commodities", q: 75, fmt: "brl" },
  { s: "WEGE3.SA", show: "WEGE3", n: "WEG", tab: "b3", group: "Industrial", q: 74, fmt: "brl" },
  { s: "ABEV3.SA", show: "ABEV3", n: "Ambev", tab: "b3", group: "Consumo", q: 73, fmt: "brl" },
  { s: "B3SA3.SA", show: "B3SA3", n: "B3", tab: "b3", group: "Financeiro", q: 72, fmt: "brl" },
  { s: "PRIO3.SA", show: "PRIO3", n: "Prio", tab: "b3", group: "Energia", q: 71, fmt: "brl" },
  { s: "SLCE3.SA", show: "SLCE3", n: "SLC Agrícola", tab: "b3", group: "Agro", q: 70, fmt: "brl" },
  { s: "SUZB3.SA", show: "SUZB3", n: "Suzano", tab: "b3", group: "Agro", q: 69, fmt: "brl" },
  { s: "AAPL", show: "AAPL", n: "Apple", tab: "global", group: "Mag7", q: 68, fmt: "usd" },
  { s: "MSFT", show: "MSFT", n: "Microsoft", tab: "global", group: "Mag7", q: 67, fmt: "usd" },
  { s: "NVDA", show: "NVDA", n: "NVIDIA", tab: "global", group: "Mag7", q: 66, fmt: "usd" },
  { s: "GOOGL", show: "GOOGL", n: "Alphabet", tab: "global", group: "Mag7", q: 65, fmt: "usd" },
  { s: "AMZN", show: "AMZN", n: "Amazon", tab: "global", group: "Mag7", q: 64, fmt: "usd" },
  { s: "META", show: "META", n: "Meta", tab: "global", group: "Mag7", q: 63, fmt: "usd" },
  { s: "BRK-B", show: "BRK.B", n: "Berkshire", tab: "global", group: "EUA", q: 62, fmt: "usd" },
  { s: "JPM", show: "JPM", n: "JPMorgan", tab: "global", group: "EUA", q: 61, fmt: "usd" },
  { s: "DE", show: "DE", n: "John Deere", tab: "global", group: "Agro", q: 60, fmt: "usd" },
  { s: "ADM", show: "ADM", n: "ADM", tab: "global", group: "Agro", q: 59, fmt: "usd" }
];
