window.YC_EDGE = "https://yc-finance-api.vercel.app";
window.YC_UNIVERSE = [
  { s: "BTC-BRL", show: "BTC", n: "Bitcoin / Real", tabs: ["fx"], group: "Cripto", q: 110, dec: 0, u: "R$", h24: true, src: ["awesome"] },
  { s: "BTC-USD", show: "BTCUSD", n: "Bitcoin / Dólar", tabs: ["fx"], group: "Cripto", q: 109, dec: 2, u: "US$", h24: true, src: ["edge", "awesome"] },
  { s: "BRL=X", show: "USDBRL", n: "Dólar / Real", tabs: ["fx"], group: "Moedas", q: 100, dec: 4, u: "R$", src: ["awesome", "edge"] },
  { s: "EURBRL=X", show: "EURBRL", n: "Euro / Real", tabs: ["fx"], group: "Moedas", q: 90, dec: 4, u: "R$", src: ["awesome", "edge"] },
  { s: "GC=F", show: "OURO", n: "Ouro · futuro COMEX", tabs: ["fx"], group: "Metal", q: 80, dec: 2, u: "US$/oz" },
  { s: "CTZ26.NYB", show: "CTZ26", n: "Algodão Dez/26", tabs: ["graos"], group: "Algodão", q: 99, dec: 2, u: "¢/lb" },
  { s: "CTZ27.NYB", show: "CTZ27", n: "Algodão Dez/27", tabs: ["graos"], group: "Algodão", q: 98, dec: 2, u: "¢/lb" },
  { s: "CTZ28.NYB", show: "CTZ28", n: "Algodão Dez/28", tabs: ["graos"], group: "Algodão", q: 97, dec: 2, u: "¢/lb" },
  { s: "ZSX26.CBT", show: "ZSX26", n: "Soja Nov/26", tabs: ["graos", "chicago"], group: "Soja", q: 96, dec: 2, u: "¢/bu" },
  { s: "ZSH27.CBT", show: "ZSH27", n: "Soja Mar/27", tabs: ["graos", "chicago"], group: "Soja", q: 95, dec: 2, u: "¢/bu" },
  { s: "ZSH28.CBT", show: "ZSH28", n: "Soja Mar/28", tabs: ["graos", "chicago"], group: "Soja", q: 94, dec: 2, u: "¢/bu" },
  { s: "ZCZ26.CBT", show: "ZCZ26", n: "Milho Dez/26", tabs: ["graos", "chicago"], group: "Milho", q: 93, dec: 2, u: "¢/bu" },
  { s: "ZWZ26.CBT", show: "ZWZ26", n: "Trigo Dez/26", tabs: ["graos", "chicago"], group: "Trigo", q: 92, dec: 2, u: "¢/bu" },
  { s: "ZWH27.CBT", show: "ZWH27", n: "Trigo Mar/27", tabs: ["graos", "chicago"], group: "Trigo", q: 91, dec: 2, u: "¢/bu" },
  { s: "ZMZ26.CBT", show: "ZMZ26", n: "Farelo de soja Dez/26", tabs: ["graos", "chicago"], group: "Farelo de soja", q: 90, dec: 2, u: "US$/t curta" },
  { s: "ZMH27.CBT", show: "ZMH27", n: "Farelo de soja Mar/27", tabs: ["graos", "chicago"], group: "Farelo de soja", q: 89, dec: 2, u: "US$/t curta" },
  { s: "ZLZ26.CBT", show: "ZLZ26", n: "Óleo de soja Dez/26", tabs: ["graos", "chicago"], group: "Óleo de soja", q: 88, dec: 2, u: "¢/lb" },
  { s: "ZLH27.CBT", show: "ZLH27", n: "Óleo de soja Mar/27", tabs: ["graos", "chicago"], group: "Óleo de soja", q: 87, dec: 2, u: "¢/lb" },
  { s: "BZ=F", show: "BRENT", n: "Brent · 1º venc.", tabs: ["graos"], group: "Energia", q: 81, dec: 2, u: "US$/bbl" },
  { s: "ITUB4.SA", show: "ITUB4", n: "Itaú", tabs: ["acoes"], group: "B3 · Bancos e bolsa", q: 79, dec: 2, u: "R$" },
  { s: "BBDC4.SA", show: "BBDC4", n: "Bradesco", tabs: ["acoes"], group: "B3 · Bancos e bolsa", q: 78, dec: 2, u: "R$" },
  { s: "BBAS3.SA", show: "BBAS3", n: "Banco do Brasil", tabs: ["acoes"], group: "B3 · Bancos e bolsa", q: 77, dec: 2, u: "R$" },
  { s: "PETR4.SA", show: "PETR4", n: "Petrobras", tabs: ["acoes"], group: "B3 · Energia e mineração", q: 76, dec: 2, u: "R$" },
  { s: "VALE3.SA", show: "VALE3", n: "Vale", tabs: ["acoes"], group: "B3 · Energia e mineração", q: 75, dec: 2, u: "R$" },
  { s: "WEGE3.SA", show: "WEGE3", n: "WEG", tabs: ["acoes"], group: "B3 · Indústria e consumo", q: 74, dec: 2, u: "R$" },
  { s: "ABEV3.SA", show: "ABEV3", n: "Ambev", tabs: ["acoes"], group: "B3 · Indústria e consumo", q: 73, dec: 2, u: "R$" },
  { s: "B3SA3.SA", show: "B3SA3", n: "B3", tabs: ["acoes"], group: "B3 · Bancos e bolsa", q: 72, dec: 2, u: "R$" },
  { s: "PRIO3.SA", show: "PRIO3", n: "Prio", tabs: ["acoes"], group: "B3 · Energia e mineração", q: 71, dec: 2, u: "R$" },
  { s: "SLCE3.SA", show: "SLCE3", n: "SLC Agrícola", tabs: ["acoes"], group: "B3 · Agro", q: 70, dec: 2, u: "R$" },
  { s: "SUZB3.SA", show: "SUZB3", n: "Suzano", tabs: ["acoes"], group: "B3 · Agro", q: 69, dec: 2, u: "R$" },
  { s: "^BVSP", show: "IBOV", n: "Ibovespa", tabs: ["acoes"], group: "Índices", q: 108, dec: 2, u: "pts" },
  { s: "^GSPC", show: "SPX", n: "S&P 500", tabs: ["acoes"], group: "Índices", q: 107, dec: 2, u: "pts" },
  { s: "^IXIC", show: "IXIC", n: "Nasdaq Composite", tabs: ["acoes"], group: "Índices", q: 106, dec: 2, u: "pts" },
  { s: "^DJI", show: "DJI", n: "Dow Jones", tabs: ["acoes"], group: "Índices", q: 105, dec: 2, u: "pts" },
  { s: "^GDAXI", show: "DAX", n: "DAX", tabs: ["acoes"], group: "Índices", q: 104, dec: 2, u: "pts" },
  { s: "^N225", show: "NIKKEI", n: "Nikkei 225", tabs: ["acoes"], group: "Índices", q: 103, dec: 2, u: "pts" },
  { s: "^FTSE", show: "FTSE", n: "FTSE 100", tabs: ["acoes"], group: "Índices", q: 102, dec: 2, u: "pts" },
  { s: "AAPL", show: "AAPL", n: "Apple", tabs: ["acoes"], group: "EUA · Big techs", q: 68, dec: 2, u: "US$" },
  { s: "MSFT", show: "MSFT", n: "Microsoft", tabs: ["acoes"], group: "EUA · Big techs", q: 67, dec: 2, u: "US$" },
  { s: "NVDA", show: "NVDA", n: "NVIDIA", tabs: ["acoes"], group: "EUA · Big techs", q: 66, dec: 2, u: "US$" },
  { s: "GOOGL", show: "GOOGL", n: "Alphabet", tabs: ["acoes"], group: "EUA · Big techs", q: 65, dec: 2, u: "US$" },
  { s: "AMZN", show: "AMZN", n: "Amazon", tabs: ["acoes"], group: "EUA · Big techs", q: 64, dec: 2, u: "US$" },
  { s: "META", show: "META", n: "Meta", tabs: ["acoes"], group: "EUA · Big techs", q: 63, dec: 2, u: "US$" },
  { s: "BRK-B", show: "BRK.B", n: "Berkshire", tabs: ["acoes"], group: "EUA · Finanças", q: 62, dec: 2, u: "US$" },
  { s: "JPM", show: "JPM", n: "JPMorgan", tabs: ["acoes"], group: "EUA · Finanças", q: 61, dec: 2, u: "US$" },
  { s: "DE", show: "DE", n: "John Deere", tabs: ["acoes"], group: "EUA · Agro", q: 60, dec: 2, u: "US$" },
  { s: "ADM", show: "ADM", n: "ADM", tabs: ["acoes"], group: "EUA · Agro", q: 59, dec: 2, u: "US$" }
];
