window.YC_EDGE = "https://yc-finance-api.vercel.app";
window.YC_UNIVERSE = [
  { s: "BTC-BRL", show: "BTC", n: "Bitcoin / Real", tab: "fx", group: "Cripto", q: 110, dec: 0, u: "R$", src: ["awesome"] },
  { s: "BTC-USD", show: "BTCUSD", n: "Bitcoin / Dólar", tab: "fx", group: "Cripto", q: 109, dec: 2, u: "US$", src: ["edge", "awesome"] },
  { s: "BRL=X", show: "USDBRL", n: "Dólar / Real", tab: "fx", group: "Câmbio", q: 100, dec: 4, u: "R$", src: ["awesome", "edge"] },
  { s: "EURBRL=X", show: "EURBRL", n: "Euro / Real", tab: "fx", group: "Câmbio", q: 90, dec: 4, u: "R$", src: ["awesome", "edge"] },
  { s: "GC=F", show: "OURO", n: "Ouro · futuro COMEX", tab: "fx", group: "Metal", q: 80, dec: 2, u: "US$/oz" },
  { s: "CTZ26.NYB", show: "CTZ26", n: "Algodão Dez/26", tab: "agro", group: "Algodão", q: 99, dec: 2, u: "¢/lb" },
  { s: "CTZ27.NYB", show: "CTZ27", n: "Algodão Dez/27", tab: "agro", group: "Algodão", q: 98, dec: 2, u: "¢/lb" },
  { s: "CTZ28.NYB", show: "CTZ28", n: "Algodão Dez/28", tab: "agro", group: "Algodão", q: 97, dec: 2, u: "¢/lb" },
  { s: "ZSX26.CBT", show: "ZSX26", n: "Soja Nov/26", tab: "agro", group: "Soja", q: 96, dec: 2, u: "¢/bu" },
  { s: "ZSH27.CBT", show: "ZSH27", n: "Soja Mar/27", tab: "agro", group: "Soja", q: 95, dec: 2, u: "¢/bu" },
  { s: "ZSH28.CBT", show: "ZSH28", n: "Soja Mar/28", tab: "agro", group: "Soja", q: 94, dec: 2, u: "¢/bu" },
  { s: "ZCZ26.CBT", show: "ZCZ26", n: "Milho Dez/26", tab: "agro", group: "Milho", q: 93, dec: 2, u: "¢/bu" },
  { s: "BZ=F", show: "BRENT", n: "Brent · 1º venc.", tab: "agro", group: "Energia", q: 81, dec: 2, u: "US$/bbl" },
  { s: "ITUB4.SA", show: "ITUB4", n: "Itaú", tab: "b3", group: "Bancos", q: 79, dec: 2, u: "R$" },
  { s: "BBDC4.SA", show: "BBDC4", n: "Bradesco", tab: "b3", group: "Bancos", q: 78, dec: 2, u: "R$" },
  { s: "BBAS3.SA", show: "BBAS3", n: "Banco do Brasil", tab: "b3", group: "Bancos", q: 77, dec: 2, u: "R$" },
  { s: "PETR4.SA", show: "PETR4", n: "Petrobras", tab: "b3", group: "Energia", q: 76, dec: 2, u: "R$" },
  { s: "VALE3.SA", show: "VALE3", n: "Vale", tab: "b3", group: "Commodities", q: 75, dec: 2, u: "R$" },
  { s: "WEGE3.SA", show: "WEGE3", n: "WEG", tab: "b3", group: "Industrial", q: 74, dec: 2, u: "R$" },
  { s: "ABEV3.SA", show: "ABEV3", n: "Ambev", tab: "b3", group: "Consumo", q: 73, dec: 2, u: "R$" },
  { s: "B3SA3.SA", show: "B3SA3", n: "B3", tab: "b3", group: "Financeiro", q: 72, dec: 2, u: "R$" },
  { s: "PRIO3.SA", show: "PRIO3", n: "Prio", tab: "b3", group: "Energia", q: 71, dec: 2, u: "R$" },
  { s: "SLCE3.SA", show: "SLCE3", n: "SLC Agrícola", tab: "b3", group: "Agro", q: 70, dec: 2, u: "R$" },
  { s: "SUZB3.SA", show: "SUZB3", n: "Suzano", tab: "b3", group: "Agro", q: 69, dec: 2, u: "R$" },
  { s: "^BVSP", show: "IBOV", n: "Ibovespa", tab: "global", group: "Índices", q: 108, dec: 2, u: "pts" },
  { s: "^GSPC", show: "SPX", n: "S&P 500", tab: "global", group: "Índices", q: 107, dec: 2, u: "pts" },
  { s: "^IXIC", show: "NDX", n: "Nasdaq", tab: "global", group: "Índices", q: 106, dec: 2, u: "pts" },
  { s: "^DJI", show: "DJI", n: "Dow Jones", tab: "global", group: "Índices", q: 105, dec: 2, u: "pts" },
  { s: "^GDAXI", show: "DAX", n: "DAX", tab: "global", group: "Índices", q: 104, dec: 2, u: "pts" },
  { s: "^N225", show: "NIKKEI", n: "Nikkei 225", tab: "global", group: "Índices", q: 103, dec: 2, u: "pts" },
  { s: "^FTSE", show: "FTSE", n: "FTSE 100", tab: "global", group: "Índices", q: 102, dec: 2, u: "pts" },
  { s: "AAPL", show: "AAPL", n: "Apple", tab: "global", group: "Mag7", q: 68, dec: 2, u: "US$" },
  { s: "MSFT", show: "MSFT", n: "Microsoft", tab: "global", group: "Mag7", q: 67, dec: 2, u: "US$" },
  { s: "NVDA", show: "NVDA", n: "NVIDIA", tab: "global", group: "Mag7", q: 66, dec: 2, u: "US$" },
  { s: "GOOGL", show: "GOOGL", n: "Alphabet", tab: "global", group: "Mag7", q: 65, dec: 2, u: "US$" },
  { s: "AMZN", show: "AMZN", n: "Amazon", tab: "global", group: "Mag7", q: 64, dec: 2, u: "US$" },
  { s: "META", show: "META", n: "Meta", tab: "global", group: "Mag7", q: 63, dec: 2, u: "US$" },
  { s: "BRK-B", show: "BRK.B", n: "Berkshire", tab: "global", group: "EUA", q: 62, dec: 2, u: "US$" },
  { s: "JPM", show: "JPM", n: "JPMorgan", tab: "global", group: "EUA", q: 61, dec: 2, u: "US$" },
  { s: "DE", show: "DE", n: "John Deere", tab: "global", group: "Agro", q: 60, dec: 2, u: "US$" },
  { s: "ADM", show: "ADM", n: "ADM", tab: "global", group: "Agro", q: 59, dec: 2, u: "US$" }
];
